error handling extended and improved

diff --git a/bin/snow b/bin/snow
--- a/bin/snow
+++ b/bin/snow
@@ -8,8 +8,10 @@ SNOWPATH=$(dirname "$0")
 PROGNAME=$(basename "$0")
 # Load the configuration
 CONFIG_FILE=$SNOWPATH/../etc/snow.conf
+ENTERPRISE_EXTENSIONS=$SNOWPATH/enterprise_extensions.sh
 SNOW_DOMAINS=$SNOWPATH/../etc/domains.conf
 SELF_ACTIVE_DOMAINS=$(cat $SNOW_DOMAINS | grep -v ^# | gawk '{print $1}' || echo "no gawk")
+HAS_EE=false
 opt1=$1
 opt2=$2
 opt3=$3
@@ -19,6 +21,11 @@ opt5=$5
 if [[ -f $CONFIG_FILE ]]; then
     source $CONFIG_FILE
     export PDSH_RCMD_TYPE
+fi
+
+if [[ -f $ENTERPRISE_EXTENSIONS ]]; then
+    source $ENTERPRISE_EXTENSIONS
+    HAS_EE=true
 fi
 
 if ! [[ -d $SNOWROOT/log ]]; then
@@ -40,17 +47,15 @@ Usage: snow [function] <option|domain|server>
 
 Function List:
 
-    * config                         | updates the sNow! configuration based on the snow.conf, /etc/hosts and active-domains.conf
-    * update tools                   | updates the sNow! Tools from the public HPCNow! GIT repo (only available in sNow! Enterprise Edition)
-    * update configspace             | updates configuration files from private git (only available in sNow! Enterprise Edition)
+    * config                         | updates the sNow! configuration based on the changes applied in snow.conf and domains.conf
+    * update tools                   | updates the sNow! Tools 
+    * update configspace             | updates configuration files from private git 
     * update snow_template           | updates the sNow! image used to create new domains
-    * update <domain|server>         | updates specific domain or server
     * deploy <domain|server>         | deploy specific domain/server 
-    * clone <server> <image_name>    | clone server with specific image file (only available in sNow! Enterprise Edition) 
-    * list                           | list current services and the status
-    * takeover                       | migrates domains and critical services to other sNow nodes
+    * list                           | list current domains (services) and their status
+    * takeover                       | migrates domains and critical services to other sNow nodes (only available in sNow! Enterprise Edition)
     * boot <domain|server>           | boot specific domain or server
-    * boot services                  | boot all the services (not available under sNow! HA)
+    * boot domains                   | boot all the domains (all services not available under sNow! HA)
     * boot cluster <clustername>     | boot all the compute nodes of the selected cluster (by default 20 nodes at once)
     * reboot <domain|server>         | reboot specific domain or server
     * shutdown <domain|server>       | shutdown specific domain or server
@@ -68,12 +73,7 @@ Examples:
 "
 }
 
-#function check_interfaces() {
-#ip show ${BRIDGEMAP[xpub0]}
-#}
-
 function config() {
-#check_interfaces
 if ! [[ -f $SNOW_DOMAINS ]]; then
     echo "No $SNOW_DOMAINS found"
 else
@@ -82,6 +82,12 @@ else
     cat $SNOWROOT/snow-tools/etc/active-domains.conf | grep -v ^# |  gawk '{print $0}'
 fi
 }
+
+if [ ! $HAS_EE ]; then
+    function takeover() {
+        echo "The takeover feature is only available in sNow! Enterprise Edition"
+    }
+fi
 
 function update_tools() {
 if ! [[ -d $SNOWROOT/snow-tools ]]; then
@@ -137,6 +143,14 @@ function xen_create() {
             exit 1
         else
             FORCE="--force"
+        fi
+    else
+        IMG_STATUS=$(cat $SNOW_DOMAINS | grep "$opt2")
+        if [[ ! $IMG_STATUS ]]; then
+            echo "The domain $1 is NOT available in the $SNOW_DOMAINS."
+            exit 1
+        else
+            echo "Deploying the domain $1. It can take few minutes. Please wait!"
         fi
     fi
 
@@ -199,6 +213,7 @@ function deploy() {
             fi
             if (( $NLENG > 0 )); then
                 echo "Deploying node range $1 ... This will take a while, Please wait"
+                #parallel -j $BLOCKN snow check_host_status "$NPREFIX{}-bmc" ::: $(eval echo "{${NRANK[0]}..${NRANK[1]}}")
                 deploy_copy $DEPLOYTMPL
                 parallel -j $BLOCKN \
                 echo "Deploying node : $NPREFIX{} ... Please wait" \; \
@@ -211,6 +226,7 @@ function deploy() {
                 echo "Setting up dis as boot device... Please wait"
                 deploy_copy $DEFAULTBOOT
             else
+                check_host_status $1-bmc
                 cp -p $SNOWROOT/OS/deploy/pxelinux.cfg/$DEPLOYTMPL $SNOWROOT/OS/deploy/pxelinux.cfg/$(gethostip $1 | gawk '{print $3}')
                 ipmitool -I $IPMITYPE -H $1-bmc -U $IPMIUSER -P $IPMIPWD power reset
                 sleep 5
@@ -226,16 +242,17 @@ function deploy() {
     fi
 }
 
-function update() {
-    echo update
-}
 
 function list() {
     xl list $opt2
 }
 
-function takeover() {
-    echo takeover
+
+function check_host_status(){
+    if ! ping -c 1 $1 &> /dev/null 
+        echo "The host $1 is not responsive. Please check the host name, DNS server or /etc/hosts."
+        exit 1
+    fi
 }
 
 function boot() {
@@ -245,7 +262,12 @@ function boot() {
     fi
     get_server_distribution $1
     if (($IS_VM)) ; then
-        xl create $SNOWROOT/snow-tools/etc/domains/${1}${DOM_EXT}.cfg
+        if [[ -f $SNOWROOT/snow-tools/etc/domains/${1}${DOM_EXT}.cfg ]]; then 
+            xl create $SNOWROOT/snow-tools/etc/domains/${1}${DOM_EXT}.cfg
+        else
+            echo "The domain $1 needs to be deployed first: Execute : snow deploy $i"
+            exit 1
+        fi
     else
         node_rank $1
         BLOCKN=${2:-$BLOCKN}
@@ -257,6 +279,7 @@ function boot() {
             ipmitool -I $IPMITYPE -H "$NPREFIX{}-bmc" -U $IPMIUSER -P $IPMIPWD power on \
             ::: $(eval echo "{${NRANK[0]}..${NRANK[1]}}")
         else 
+            check_host_status $1-bmc
             ipmitool -I $IPMITYPE -H $1-bmc -U $IPMIUSER -P $IPMIPWD power on
         fi
     fi
@@ -272,12 +295,10 @@ function get_server_distribution(){
     fi
 }
 
-function boot_services() {
-    #get_server_distribution 
+function boot_domains() {
     for i in $(SELF_ACTIVE_DOMAINS)
     do 
-        #ssh server[$i] xl create $SNOWROOT/etc/xen/$i.cfg
-        xl create $SNOWROOT/etc/xen/$i.cfg
+        boot $i
     done
 }
 
@@ -317,7 +338,7 @@ function nshutdown() {
         echo "ERROR: No domain(s) or node(s) to shutdown."
         exit 1
     fi
-    pdsh -w $1 halt
+    pdsh -w $1 systemctl poweroff
 }
 
 function shutdown_cluster() {
@@ -347,6 +368,7 @@ function ndestroy() {
             ipmitool -I $IPMITYPE -H "$NPREFIX{}-bmc" -U $IPMIUSER -P $IPMIPWD power off \
             ::: $(eval echo "{${NRANK[0]}..${NRANK[1]}}")
         else
+            check_host_status $1-bmc
             ipmitool -I $IPMITYPE -H $1-bmc -U $IPMIUSER -P $IPMIPWD power off
         fi
     fi
@@ -361,6 +383,7 @@ function nconsole() {
     if (($IS_VM)) ; then
         xl console $1
     else
+        check_host_status $1-bmc
         ipmitool -I $IPMITYPE -H $1-bmc -U $IPMIUSER -P $IPMIPWD sol deactivate
         sleep 1
         ipmitool -I $IPMITYPE -H $1-bmc -U $IPMIUSER -P $IPMIPWD sol activate
@@ -398,17 +421,12 @@ case $opt1 in
                 update_xen_image
             ;;
             *)
-                update $opt3
+                echo "Update available options : update_tools, configspace, snow_template"
             ;;
         esac
     ;;
     deploy)
         deploy $opt2 $opt3 $opt4 $opt5
-    ;;
-    clone)
-        echo "Option only available in sNow! Enterprise Edition. Visit www.hpcnow.com"
-        exit 1
-        #clone $opt2 $opt3
     ;;
     create)
         case $opt2 in
@@ -428,8 +446,8 @@ case $opt1 in
     ;;
     boot)
         case $opt2 in
-            services)  
-                boot_services $opt3 
+            domains)  
+                boot_domains $opt3 
             ;;
             cluster)
                 boot_cluster $opt3 $opt4 $opt5 
